---
name: Continuous Deployment

on:
  push:
    branches:
      - 'production'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn install'
      - run: 'yarn test'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    env:
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      URL: bot@server.interflux.com
      ROOT: /var/www/app.interflux.com
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ~/.ssh
      - run: 'echo "$PRIVATE_KEY" > ~/.ssh/bot@server.interflux.com'
      - run: ssh-keyscan -H server.interflux.com > ~/.ssh/known_hosts
      - run: chmod 0755 ~/.ssh/
      - run: chmod 600 ~/.ssh/bot@server.interflux.com
      - run: chmod 644 ~/.ssh/known_hosts
      - run: ssh $URL "cd $ROOT; git checkout production; git pull"
      - run: ssh $URL "cd $ROOT; nvm install"
      - run: ssh $URL "cd $ROOT; yarn install"
      - run: ssh $URL "cd $ROOT; yarn build"

      # For sanity checking the deploy we'll need pup to pull in interpet the live HTML
      - run: sudo apt-get install pup

      # The Git revision of this build
      - run: echo "BUILD_REVISION=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      # The Git revision currently live and served by Ember Fastboot
      - run: echo "LIVE_REVISION=$(curl 'https://new.interflux.com/en/product/IF-2005M' | pup 'meta[name="git-revision"] attr{content}')"

      # Fail the work flow, something is wrong.
      - name: 'Sanity check: FAIL'
        run: exit -1
        if: env.BUILD_REVISION != env.LIVE_REVISION

      # All green, deploy was successful!
      - name: 'Sanity check: PASS'
        if: env.BUILD_REVISION == env.LIVE_REVISION
        run: exit 0
